#version 450

// Particle positions
layout(set = 0, binding = 0) readonly buffer PBuffer {
    vec4 pos[]; // particle positions
};

// 3D scalar field stored as float image
layout(set = 1, binding = 0, r32f) uniform writeonly image3D field;

// Uniforms for grid and field settings
layout(set = 2, binding = 0) uniform UBO {
    uvec3 size;   // grid size: (x, y, z)
    int p0;

    float cellSize;
    float radius;
    int p1, p2;
};


layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pos.length()) return;

    vec3 p = pos[i].xyz;

    float r = radius;
    float cs = cellSize;

    // Compute affected voxel range in grid
    ivec3 minV = ivec3(floor((p - r) / cs));
    ivec3 maxV = ivec3(ceil((p + r) / cs));

    // Clamp bounds to grid size
    minV = clamp(minV, ivec3(0), ivec3(size - 1u));
    maxV = clamp(maxV, ivec3(0), ivec3(size - 1u));

    // Accumulate weights into scalar field
    for (int z = minV.z; z <= maxV.z; ++z) {
        for (int y = minV.y; y <= maxV.y; ++y) {
            for (int x = minV.x; x <= maxV.x; ++x) {

                vec3 vc = (vec3(x, y, z) + 0.5) * cs; // voxel center
                float d = distance(p, vc);
                if (d > r) continue;

                float w = 1.0 - (d / r); // linear falloff
                imageStore(field, ivec3(x, y, z), vec4(w, 0.0, 0.0, 1.0));
            }
        }
    }
}
