#version 450
#extension GL_EXT_scalar_block_layout : enable

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec3 position;
    float mass;
    vec3 velocity;
    float volume_0;
    mat3 deform_elastic;
    mat3 deform_plastic;
    mat3 deform_affine;
};

struct GridNode {
    vec3 force;
    float mass;
    vec3 momentum;
    vec3 velocity_star;
    vec3 velocity;
};

layout(std430, set = 1, binding = 0) buffer ReadWriteBuffers {
    GridNode grid[512];
    Particle particles[];
};

layout(std430, set = 2, binding = 0) uniform UBO {
    vec3 u_grid_origin;
    float u_grid_spacing; // h
    vec3 u_grid_dimension;
    float u_particles_per_cell;
    float u_initial_density;
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec3 u_gravity;
    float u_co_floor_y;
    vec3 u_co_normal;
    float u_co_mu;

    float u_D_inv; // 3.0 / h * h
    float time;
};

void main() {
    ivec3 node_pos_local = ivec3(gl_GlobalInvocationID.xyz);
    if (any(lessThan(node_pos_local, ivec3(0))) || any(greaterThanEqual(node_pos_local, u_grid_dimension))) {
        return;
    }
    uint node_id = uint(
            node_pos_local.x 
            + node_pos_local.y * node_pos_local.x 
            + node_pos_local.z * node_pos_local.x * node_pos_local.y);

    grid[node_id].mass = 0.0;
    grid[node_id].momentum = vec3(0.0);
    grid[node_id].force = vec3(0.0);
    grid[node_id].velocity = vec3(0.0);
    grid[node_id].velocity_star = vec3(0.0);
}
