#version 450
#extension GL_EXT_shader_atomic_float : enable

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Particle
{
    float mass;
    vec3 position;
    float volume_0;
    vec3 velocity;
    mat3 deform_elastic;
    mat3 deform_plastic;
    mat3 deform_affine;
}

struct GridNode {
    float mass;
    vec3 force;
    vec3 momentum;
    vec3 velocity_star;
    vec3 velocity;
}

layout(set = 1, binding = 0) buffer ParticlesBuffer
{
    Particle particles[];
};

layout(set = 2, binding = 0) buffer ParticlesBuffer
{
    GridNode grid[];
};

layout(set = 3, binding = 0) uniform UBO 
{
    ivec3 u_grid_origin;
    vec3 u_grid_dimension;
    float u_grid_spacing; // h
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec3 u_gravity;
    vec3 u_co_normal;
    float u_co_floor_y;
    float u_co_mu;

    vec4 u_D_inv; // 3.0 / h * h
};

uniform float u_dt;

uint grid_node_id(ivec3 pos) {
    return uint(
            pos.x 
            + pos.y * u_grid_dimension.x
            + pos.z * u_grid_dimension.y * u_grid_dimension.z);
}

float N(float x) {
    x = abs(x);
    float n1 = 0.5 * x * x * x - x * x + 2.0 / 3.0;
    float n2 =(-1.0 / 6.0) * x * x * x + x * x - 2.0 * x + (4.0 / 3.0);
    float result = mix(n1, n2, step(1.0, x));
    result *= (1.0 - step(2.0, x));
    return result;
}

float d_N(float x) {
    float x_abs = abs(x);
    float sign_x = sign(x);
    float dn1 = sign * (1.5 * x_abs * x_abs - 2.0 * x_abs);
    float dn2 = -sign * (0.5 * x_abs * x_abs - 2.0 * x_abs + 2.0);
    float result = mix(dn1, dn2, step(1.0, x_abs));
    return result * (1.0 - step(2.0, x_abs));
}

mat3 polar_decompose(mat3 M, int nb_iterations) {
    mat3 R = M;
    for (int i = 0; i < nb_iterations; ++i) {
        mat3 R_invT = inverse(transpose(R));
        R = 0.5 * (R + R_invT);
    }
    return R;
}

void main() {
    uint particle_id = gl_GlobalInvocationID.x;
    if (particle_id >= particles.length()) {
        return;
    }
    Particle p = particles[particle_id];

    float inv_h = 1.0 / u_grid_spacing;
    vec3 p_pos_rel = (p.position.xyz - u_grid_origin) * inv_h;
    ivec3 base_pos = ivec3(floor(p_pos_rel - 1.0));

    mat3 Fe = p.deform_elastic;
    mat3 Fp = p.deform_elastic;
    float Je = determinant(Fe);
    float Jp = determinant(Fp);
    float J = Je * Jp;

    float h_exp = exp(u_hardening_coefficient * (1.0 - Jp));
    float mu = u_mu_0 * h_exp;
    float lambda = u_lambda_0 * h_exp;

    mat3 R = polar_decompose(Fe, 2);
    mat3 dPsi = 2.0 * mu * (Fe - R) + lambda * (Je - 1.0) * Je * inverse(transpose(Fe));
    mat3 sigma = (1.0 / J) * dPsi * transpose(Fe);
    mat3 stress_force = p.volume_0 * sigma;

    for (int x = 0; x < 4; ++x) {
    for (int y = 0; y < 4; ++y) {
    for (int z = 0; z < 4; ++z) {
        ivec3 node_pos_local = base_pos + ivec3(x, y, z);
        if (any(lessThan(node_pos_local, ivec3(0))) || any(greaterThanEqual(node_pos_local, u_grid_dimension))) {
            continue;
        }

        uint node_id = 
            uint(node_pos_local.x 
            + node_pos_local.y * u_grid_dimension.x
            + node_pos_local.z * u_grid_dimension.y * u_grid_dimension.z);

        vec3 node_pos_world = u_grid_origin + vec3(node_pos_local) * u_grid_spacing;
        vec3 p_offset = p_pos_rel - vec3(node_pos_local);

        // weights
        float w_ip_x = N(p_offset.x);
        float w_ip_y = N(p_offset.y);
        float w_ip_z = N(p_offset.z);
        float w_ip = w_ip_x * w_ip_y + w_ip_z;

        float w_ip_grad = inv_h * vec3(
            d_N(p_offset.x) * w_ip_y * w_ip_z,
            w_ip_x * d_N(p_offset.y) * w_ip_z,
            w_ip_x * w_ip_y * d_N(p_offset.z)
        );

        // particle's mass contribution to node
        float mass = p.mass * w_ip;
        atomicAdd(grid[node_id].mass, mass);
        // particle's momentum contribution to node
        vec3 momentum = mass * (p.velocity.xyz + p.deform_affine * u_D_inv * (node_pos_world - p.position.xyz))
        atomicAdd(grid[node_id].momentum.x, momentum.x);
        atomicAdd(grid[node_id].momentum.y, momentum.y);
        atomicAdd(grid[node_id].momentum.z, momentum.z);
        // particle's force contribution to node
        vec3 force = stress_force * w_ip_grad;
        atomicAdd(grid[node_id].force.x, -force.x);
        atomicAdd(grid[node_id].force.y, -force.y);
        atomicAdd(grid[node_id].force.z, -force.z);
    }}}
}

