#version 450
#extension GL_EXT_shader_atomic_float : enable

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Particle
{
    float mass;
    vec3 position;
    float volume_0;
    vec3 velocity;
    mat3 deform_elastic;
    mat3 deform_plastic;
    mat3 deform_affine;
}

struct GridNode {
    float mass;
    vec3 force;
    vec3 momentum;
    vec3 velocity_star;
    vec3 velocity;
}

layout(set = 1, binding = 0) buffer ParticlesBuffer
{
    Particle particles[];
};

layout(set = 2, binding = 0) buffer ParticlesBuffer
{
    GridNode grid[];
};

layout(set = 3, binding = 0) uniform UBO 
{
    ivec3 u_grid_origin;
    vec3 u_grid_dimension;
    float u_grid_spacing; // h
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec3 u_gravity;
    vec3 u_co_normal;
    float u_co_floor_y;
    float u_co_mu;

    vec4 u_D_inv; // 3.0 / h * h
};

uniform float u_dt;


void main() 
{
    ivec3 node_pos_local = ivec3(gl_GlobalInvocationID.xyz);
    if (any(lessThan(node_pos_local, ivec3(0))) || any(greaterThanEqual(node_pos_local, u_grid_dimension))) {
        return;
    }
    uint node_id = uint(
            node_pos_local.x 
            + node_pos_local.y * node_pos_local.x 
            + node_pos_local.z * node_pos_local.x * node_pos_local.y);

    GridNode node = grid[node_id];
    if (node.mass > 0.0) {
        vec3 f_ext = node.mass * params.gravity;
        vec3 f_i = node.force + f_ext;
        node.velocity_star = node.velocity + u_dt * f_i / node.mass;

        vec3 node_pos_world = u_grid_origin + vec3(node_pos_local) * u_grid_spacing;
        if (node_pos_world.y < u_co_floor_y) {
            vec3 v_rel = node->velocity_star;
            double v_n = dot(v_rel, u_co_normal) ;

            if (v_n < 0.0) {
                vec3 v_t = v_rel - (v_n * u_co_normal);
                double v_t_norm = length(v_t);

                if (v_t_norm <= -u_co_mu * v_n) {
                    v_rel = vec3(0.0);
                }
                else {
                    v_rel = v_t + u_co_mu * v_n * (v_t / v_t_norm);
                }

                node.velocity_star = v_rel;
            }
        }

        grid[node_idx] = node;
    }
    else {
        grid[node_idx].velocity = vec3(0.0);
        grid[node_idx].velocity_star = vec3(0.0);
    }
}
