#version 450
#extension GL_EXT_scalar_block_layout : enable

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec3 position;
    float mass;
    vec3 velocity;
    float volume_0;
    mat3 deform_elastic;
    mat3 deform_plastic;
    mat3 deform_affine;
};

struct GridNode {
    vec3 force;
    float mass;
    vec3 momentum;
    vec3 velocity_star;
    vec3 velocity;
};

layout(std430, set = 1, binding = 0) buffer ReadWriteBuffers {
    GridNode grid[512];
    Particle particles[];
};

layout(std430, set = 2, binding = 0) uniform UBO {
    vec3 u_grid_origin;
    float u_grid_spacing; // h
    vec3 u_grid_dimension;
    float u_particles_per_cell;
    float u_initial_density;
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec3 u_gravity;
    float u_co_floor_y;
    vec3 u_co_normal;
    float u_co_mu;

    float u_D_inv; // 3.0 / h * h
    float time;
};

float N(float x) {
    x = abs(x);
    float n1 = 0.5 * x * x * x - x * x + 2.0 / 3.0;
    float n2 =(-1.0 / 6.0) * x * x * x + x * x - 2.0 * x + (4.0 / 3.0);
    float result = mix(n1, n2, step(1.0, x));
    result *= (1.0 - step(2.0, x));
    return result;
}

float d_N(float x) {
    float x_abs = abs(x);
    float sign_x = sign(x);
    float dn1 = sign_x * (1.5 * x_abs * x_abs - 2.0 * x_abs);
    float dn2 = -sign_x * (0.5 * x_abs * x_abs - 2.0 * x_abs + 2.0);
    float result = mix(dn1, dn2, step(1.0, x_abs));
    return result * (1.0 - step(2.0, x_abs));
}

void main() {
    uint particle_id = gl_GlobalInvocationID.x;
    if (particle_id >= particles.length()) {
        return;
    }
    Particle p = particles[particle_id];

    float inv_h = 1.0 / u_grid_spacing;
    float inv_h3 = inv_h * inv_h * inv_h;

    vec3 p_pos_rel = (p.position.xyz - u_grid_origin) * inv_h;
    ivec3 base_pos = ivec3(floor(p_pos_rel - 1.0));
    float mass = u_initial_density * u_grid_spacing * u_grid_spacing * u_grid_spacing / u_particles_per_cell;
    float rho_p = 0.0;

    for (int x = 0; x < 4; ++x) {
    for (int y = 0; y < 4; ++y) {
    for (int z = 0; z < 4; ++z) {
        ivec3 node_pos_local = base_pos + ivec3(x, y, z);
        if (any(lessThan(node_pos_local, ivec3(0))) || any(greaterThanEqual(node_pos_local, u_grid_dimension))) {
            continue;
        }

        uint node_id = 
            uint(node_pos_local.x 
            + node_pos_local.y * u_grid_dimension.x
            + node_pos_local.z * u_grid_dimension.y * u_grid_dimension.z);

        vec3 node_pos_world = u_grid_origin + vec3(node_pos_local) * u_grid_spacing;
        vec3 p_offset = p_pos_rel - vec3(node_pos_local);
        GridNode node = grid[node_id];

        float w_ip_x = N(p_offset.x);
        float w_ip_y = N(p_offset.y);
        float w_ip_z = N(p_offset.z);
        float w_ip = w_ip_x * w_ip_y * w_ip_z;

        vec3 w_ip_grad = inv_h * vec3(
            d_N(p_offset.x) * w_ip_y * w_ip_z,
            w_ip_x * d_N(p_offset.y) * w_ip_z,
            w_ip_x * w_ip_y * d_N(p_offset.z)
        );

        rho_p += w_ip * node.mass * inv_h3;
    }}}

    p.mass = mass;

    if (rho_p > 0.0) {
        p.volume_0 = mass / rho_p;
    }

    particles[particle_id] = p;
}
