#version 450

layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

struct Particle {
    vec4 position;
    vec4 velocity;
    mat4 deform_elastic;
    mat4 deform_plastic;
    mat4 deform_affine;
    float mass;
    float volume_0;
};

struct GridNode {
    vec4 force;
    vec4 momentum;
    vec4 velocity_star;
    vec4 velocity;
    int mass;
};

layout(set = 1, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(set = 1, binding = 1) buffer GridBuffer {
    GridNode grid[];
};

layout(set = 2, binding = 0) uniform UBO {
    vec4 u_grid_origin;
    vec4 u_grid_dimension;
    float u_grid_spacing; // h
    float u_particles_per_cell;
    float u_initial_density;
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec4 u_gravity;
    vec4 u_co_normal;
    float u_co_floor_y;
    float u_co_mu;

    float u_D_inv; // 3.0 / h * h
    float time;
    uint u_nb_particles;
    uint u_nb_grid_nodes;
};

void main() {
    ivec3 node_pos_local = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 grid_dimension = ivec3(u_grid_dimension.xyz);

    if (any(greaterThanEqual(node_pos_local, grid_dimension))) {
        return;
    }

    uint node_id = uint(node_pos_local.x
        + node_pos_local.y * grid_dimension.x
        + node_pos_local.z * grid_dimension.x * grid_dimension.y);

    if (node_id >= u_nb_grid_nodes) {
        return;
    }

    GridNode node = grid[node_id];
    if (node.mass > 0.0) {
        vec3 f_ext = node.mass * u_gravity.xyz;
        vec3 f_i = node.force.xyz + f_ext;
        node.velocity_star.xyz = node.velocity.xyz + time * f_i / node.mass;

        vec3 node_pos_world = u_grid_origin.xyz + vec3(node_pos_local) * u_grid_spacing;
        if (node_pos_world.y < u_co_floor_y) {
            vec3 v_rel = node.velocity_star.xyz;
            float v_n = dot(v_rel, u_co_normal.xyz) ;

            if (v_n < 0.0) {
                vec3 v_t = v_rel - (v_n * u_co_normal.xyz);
                float v_t_norm = length(v_t);

                if (v_t_norm <= -u_co_mu * v_n) {
                    v_rel = vec3(0.0);
                }
                else {
                    v_rel = v_t + u_co_mu * v_n * (v_t / v_t_norm);
                }

                node.velocity_star.xyz = v_rel;
            }
        }

        grid[node_id] = node;
    }
    else {
        grid[node_id].velocity = vec4(0.0);
        grid[node_id].velocity_star = vec4(0.0);
    }
}
