#version 450

layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

struct Particle {
    vec4 position;
    vec4 velocity;
    mat4 deform_elastic;
    mat4 deform_plastic;
    mat4 deform_affine;
    float mass;
    float volume_0;
};

struct GridNode {
    vec4 force;
    vec4 momentum;
    vec4 velocity_star;
    vec4 velocity;
    float mass;
};

layout(set = 1, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(set = 1, binding = 1) buffer GridBuffer {
    GridNode grid[];
};

layout(set = 2, binding = 0) uniform UBO {
    vec4 u_grid_origin;
    vec4 u_grid_dimension;
    float u_grid_spacing; // h
    float u_particles_per_cell;
    float u_initial_density;
    float u_mu_0;
    float u_lambda_0;
    float u_hardening_coefficient;
    float u_critical_compression;
    float u_critical_stretch;
    float u_poisson_ratio;
    float u_alpha_blend;

    vec4 u_gravity;
    vec4 u_co_normal;
    float u_co_floor_y;
    float u_co_mu;

    float u_D_inv; // 3.0 / h * h
    float time;
    uint u_nb_particles;
    uint u_nb_grid_nodes;
};

void main() {
    ivec3 node_pos_local = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 grid_dimension = ivec3(u_grid_dimension.xyz);

    if (any(greaterThanEqual(node_pos_local, grid_dimension))) {
        return;
    }

    uint node_id = uint(node_pos_local.x
        + node_pos_local.y * grid_dimension.x
        + node_pos_local.z * grid_dimension.x * grid_dimension.y);

    if (node_id >= u_nb_grid_nodes) {
        return;
    }

    grid[node_id].mass = 0.0;
    grid[node_id].momentum = vec4(0.0);
    grid[node_id].force = vec4(0.0);
    grid[node_id].velocity = vec4(0.0);
    grid[node_id].velocity_star = vec4(0.0);
}
