#version 450

layout(set = 1, binding = 0, rgba32f) uniform writeonly image2D gPosition;
layout(set = 1, binding = 1, rgba16f) uniform writeonly image2D gNormal;
layout(set = 1, binding = 2, rgba8) uniform writeonly image2D gAlbedo;

layout(set = 0, binding = 0) uniform sampler2D gModifiedDepth;


layout(set = 2, binding = 0) uniform gBufferParticlesUniform 
{
    mat4 proj;
    mat4 view;
    mat4 model;
    float radius;
    float near;
    float far;
    int id;
    vec4 color;
};

float LinearizeDepth(float depth, float near, float far)
{
    return (2.0 * near * far) / (far + near - (2.0 * depth - 1.0) * (far - near));
}

// Les offsets 3x3 du filtre de Sobel
const ivec2 offsets[9] = ivec2[](
    ivec2(-1, -1), ivec2(0, -1), ivec2(1, -1),
    ivec2(-1,  0), ivec2(0,  0), ivec2(1,  0),
    ivec2(-1,  1), ivec2(0,  1), ivec2(1,  1)
);

// Les poids de sobels dans direction X et Y
const float sobelX[9] = float[](
    -1, 0, 1,
    -2, 0, 2,
    -1, 0, 1
);
const float sobelY[9] = float[](
    -1, -2, -1,
     0,  0,  0,
     1,  2,  1
);

vec3 constructPosition(ivec2 coords, float depth, vec2 resolution, mat4 invProj, mat4 invView) {
    vec2 uv = (vec2(coords) + 0.5) / vec2(resolution); // [0,1]
    vec2 ndc = uv * 2.0 - 1.0; // [-1,1]
    vec4 clip = vec4(ndc, depth, 1.0);
    
    // Unproject to view space
    vec4 viewPos = invProj * clip;
    viewPos /= viewPos.w;

    // Transform to world space
    vec4 worldPos = invView * viewPos;
    return worldPos.xyz;
}

float constructDepth(ivec2 coords){
    float depth = texelFetch(gModifiedDepth, coords, 0).r;
    
    float z = depth * 2.0 - 1.0; // retour en NDC
    float linearDepth = (2.0 * near * far) / (far + near - z * (far - near));
    return linearDepth;
}

layout(local_size_x = 16, local_size_y = 16) in;

void main() 
{
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 resolution = imageSize(gPosition);
    mat4 invProj = inverse(proj);
    mat4 invView = inverse(view);

    vec3 dx = vec3(0.0);
    vec3 dy = vec3(0.0);

    float test_depth = texelFetch(gModifiedDepth, pixelCoords, 0).r;
    if(test_depth == 1.0) return;

    for (int i = 0; i < 9; ++i){
        ivec2 sampleCoords = pixelCoords + offsets[i];
        sampleCoords = clamp(sampleCoords, ivec2(0), ivec2(resolution) - 1);

        float sampleDepth = constructDepth(sampleCoords);
        vec3 samplePos = constructPosition(sampleCoords, sampleDepth, resolution, invProj, invView);

        dx += sobelX[i] * samplePos;
        dy += sobelY[i] * samplePos;
    }

    vec3 normal = normalize(cross(dy, dx));
    imageStore(gNormal, pixelCoords, vec4(normal, 1.0));

    float depth = constructDepth(pixelCoords);
    vec3 position = constructPosition(pixelCoords, depth, resolution, invProj, invView);
    imageStore(gPosition, pixelCoords, vec4(position.xyz, float(id)));
    imageStore(gAlbedo, pixelCoords, vec4(color.rgb, 1.0));
}
