name: CMake Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
    steps:
    - name: Install dependencies on Ubuntu
      run: >
        sudo apt-get install -y
        libegl1-mesa-dev
        libwayland-dev
        libxkbcommon-dev
        wayland-protocols
        libsdl2-dev libsdl2-2.0-0 libglew-dev
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set reusable strings
      id: strings
      run: |
        HASH=$(git submodule status | sha256sum | cut -d ' ' -f1)
        echo "Computed hash: $HASH"
        echo "cache-key=${{ runner.os }}-$HASH" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      id: cache
      with:
        key: ${{ steps.strings.outputs.cache-key }}
        path: |
          ${{ github.workspace }}/libs
          ${{ github.workspace }}/build-clang
          ${{ github.workspace }}/build-gcc
    - name: Configure CMake with GCC
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ github.workspace }}/build-gcc
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -S ${{ github.workspace }}
    - name: Build with gcc
      run: cmake --build ${{ github.workspace }}/build-gcc
    - name: Configure CMake with Clang
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ github.workspace }}/build-clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -S ${{ github.workspace }}
    - name: Build with Clang
      run: cmake --build ${{ github.workspace }}/build-clang

  build-windows:
    runs-on: windows-2025
    steps:
    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest
        version-sdl-image: 2-latest
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Configure CMake with CL
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Debug
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/build
