name: CMake Build

on: [push]

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-submodule-key: ${{ steps.strings.outputs.cache-submodule-key }}
      cache-builds-key: ${{ steps.strings.outputs.cache-builds-key }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set reusable strings
      id: strings
      run: |
        HASH=$(git submodule status | sha256sum | cut -d ' ' -f1)
        echo "Computed hash: $HASH"
        echo "cache-submodule-key=${{ runner.os }}-submodules-$HASH" >> $GITHUB_OUTPUT
        echo "cache-builds-key=${{ runner.os }}-builds-${{ hashFiles('CMakeLists.txt') }}-$HASH" >> $GITHUB_OUTPUT
    - uses: actions/cache/restore@v4
      id: cache
      with:
        key: ${{ steps.strings.outputs.cache-submodule-key }}
        path: ${{ github.workspace }}/libs
        lookup-only: true
    - uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        key: ${{ steps.strings.outputs.cache-submodule-key }}
        path: ${{ github.workspace }}/libs

  build-linux:
    runs-on: ubuntu-latest
    needs: setup-cache
    env:
      BUILD_TYPE: Debug
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restore submodules
      uses: actions/cache/restore@v4
      id: submodulecache
      with:
        key: ${{ needs.setup-cache.outputs.cache-submodule-key }}
        path: ${{ github.workspace }}/libs
        fail-on-cache-miss: true
    - name: Install dependencies on Ubuntu
      run: >
        sudo apt-get install -y
        libegl1-mesa-dev
        libwayland-dev
        libxkbcommon-dev
        wayland-protocols
    - uses: actions/cache/restore@v4
      name: Restore build's artifacts
      id: cache
      with:
        key: ${{ needs.setup-cache.outputs.cache-builds-key }}
        path: |
          ${{ github.workspace }}/build-clang
          ${{ github.workspace }}/build-gcc
    - name: Configure CMake with GCC
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ github.workspace }}/build-gcc
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -S ${{ github.workspace }}
    - name: Configure CMake with Clang
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ github.workspace }}/build-clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -S ${{ github.workspace }}
    - name: Build with gcc
      run: cmake --build ${{ github.workspace }}/build-gcc
    - name: Build with Clang
      run: cmake --build ${{ github.workspace }}/build-clang
    - uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        key: ${{ needs.setup-cache.outputs.cache-builds-key }}
        path: |
          ${{ github.workspace }}/build-clang
          ${{ github.workspace }}/build-gcc

  build-windows:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Configure CMake with CL
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/build
