name: CMake Build

on: [push]

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    outputs:
      submodule-hash: ${{ steps.strings.outputs.submodule-hash }}
      build-output-dir: ${{ steps.strings.outputs.build-output-dir }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        HASH=$(git submodule status | sha256sum | cut -d ' ' -f1)
        echo "Computed hash: $HASH"
        echo "submodule-hash=$HASH" >> $GITHUB_OUTPUT
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - uses: actions/cache/restore@v4
      id: cache
      with:
        key: submodules-${{ steps.strings.outputs.submodule-hash }}
        path: ${{ github.workspace }}/libs
        lookup-only: true

    - uses: actions/cache/save@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        key: submodules-${{ steps.strings.outputs.submodule-hash }}
        path: ${{ github.workspace }}/libs

  build-linux:
    runs-on: ${{ matrix.os }}
    needs: setup-cache
    strategy:
      matrix:
        os: [ubuntu-latest]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Restore submodules
      uses: actions/cache/restore@v4
      id: submodulecache
      with:
        key: submodules-${{ needs.setup-cache.outputs.submodule-hash }}
        path: ${{ github.workspace }}/libs
        fail-on-cache-miss: true
    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols
    - uses: actions/cache/restore@v4
      name: Restore build's artifacts
      id: cache
      with:
        key: ${{ runner.os }}-${{ matrix.cpp_compiler }}-${{ hashFiles('CMakeLists.txt') }}
        path: ${{ needs.setup-cache.outputs.build-output-dir }}
    - name: Configure CMake
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ needs.setup-cache.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ needs.setup-cache.outputs.build-output-dir }}

    - uses: actions/cache/save@v4
      with:
        key: ${{ runner.os }}-${{ matrix.cpp_compiler }}-${{ hashFiles('CMakeLists.txt') }}
        path: ${{ needs.setup-cache.outputs.build-output-dir }}

  build-windows:
    runs-on: windows-2025
    needs: build-linux
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        HASH=$(git submodule status | sha256sum | cut -d ' ' -f1)
        echo "Computed hash: $HASH"
        echo "submodule-hash=$HASH" >> $GITHUB_OUTPUT
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - uses: actions/cache/restore@v4
      id: subcache
      with:
        key: submodules-windows-${{ steps.strings.outputs.submodule-hash }}
        path: ${{ github.workspace }}/libs

    - uses: actions/cache/save@v4
      if: steps.subcache.outputs.cache-hit != 'true'
      with:
        key: submodules-windows-${{ steps.strings.outputs.submodule-hash }}
        path: ${{ github.workspace }}/libs
    - uses: actions/cache/restore@v4
      name: Restore build's artifacts
      id: cache
      with:
        key: ${{ runner.os }}-cl-${{ hashFiles('CMakeLists.txt') }}
        path: ${{ steps.strings.outputs.build-output-dir }}
    - name: Configure CMake
      if: steps.cache.outputs.cache-hit != 'true'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - uses: actions/cache/save@v4
      with:
        key: ${{ runner.os }}-cl-${{ hashFiles('CMakeLists.txt') }}
        path: ${{ steps.strings.outputs.build-output-dir }}
